CREATE TABLE [MiscellaneousLocal] (
  [OpenAge] BYTE ,
  [ImportLocation] VARCHAR (100),
  [ExportLocation] VARCHAR (50),
  [ImportFormat] BYTE ,
  [ExcelFormat] BIT ,
  [TextFormat] BIT ,
  [CESfuture] BIT ,
  [CESactive] BIT ,
  [CEScompleted] BIT ,
  [CESpromoted] BIT ,
  [CESflevel] VARCHAR (5),
  [CESmale] BIT ,
  [CESfemale] BIT ,
  [CESage] VARCHAR (20),
  [CESevent] VARCHAR (30),
  [CESheatcomplete] VARCHAR (2),
  [CESevent#] VARCHAR (20),
  [License] VARCHAR (100),
  [CarnivalFooter] VARCHAR (100),
  [HouseType] LONG ,
  [ActiveCarnival] VARCHAR (50),
  [CompetitorPlaces] SHORT ,
  [AgeChampions] SHORT ,
  [CompBulkField] VARCHAR (50),
  [CompBulkOp] VARCHAR (50),
  [CompBulkValue] VARCHAR (50),
  [ShowDialog] BIT ,
  [AlertToRecord] BIT ,
  [Date] DATETIME ,
  [CESmixed] BIT 
)
