CREATE TABLE [Misc-Statistics] (
  [Overall] BIT ,
  [Age] BIT ,
  [Gender] BIT ,
  [Gender-Age] BIT ,
  [Place] BIT ,
  [Cumulative] BIT ,
  [CompetitorResults] BIT ,
  [EventResults] BIT ,
  [CurrentRecords] BIT ,
  [CurrentRecords-Mini] BIT ,
  [Recordset] BIT ,
  [RecordDate] DATETIME ,
  [CompetitorPlace] BIT ,
  [Fastest] BIT ,
  [Longest] BIT ,
  [AgeChampions] BIT ,
  [AgeChampionAllDivs] BIT ,
  [AgeChampionNumber] SHORT ,
  [CompetitorList] BIT ,
  [CompetitorEvents] BIT ,
  [NumberOfRecords] SHORT ,
  [Non-Participants] BIT 
)
